name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build (${{ matrix.configuration }})
      run: dotnet build --no-restore -c ${{ matrix.configuration }}

    - name: Upload build artifacts (${{ matrix.configuration }})
      uses: actions/upload-artifact@v4
      with:
        name: Cheeseman-Games-${{ matrix.configuration }}
        path: bin\${{ matrix.configuration }}\**\*
